const std = @import("std");
const ForkSeq = @import("config").ForkSeq;

pub const Handler = enum {
    deposit_with_reorg,
    ex_ante,
    get_head,
    get_proposer_head,
    on_block,
    on_merge_block,
    reorg,
    should_override_forkchoice_update,
    withholding,

    pub fn suiteName(self: Handler) []const u8 {
        return @tagName(self) ++ "/pyspec_tests";
    }
};

pub const handlers = std.enums.values(Handler);

pub const header =
    \\// This file is generated by write_spec_tests.zig.
    \\// Do not commit changes by hand.
    \\
    \\const std = @import("std");
    \\const Node = @import("persistent_merkle_tree").Node;
    \\const ForkSeq = @import("config").ForkSeq;
    \\const active_preset = @import("preset").active_preset;
    \\const spec_test_options = @import("spec_test_options");
    \\const ForkChoiceRunner = @import("../runner/fork_choice.zig");
    \\
    \\const allocator = std.testing.allocator;
    \\const pool_size = if (active_preset == .mainnet) 10_000_000 else 1_000_000;
    \\
    \\
;

const test_template =
    \\test "{s} fork_choice {s} {s}" {{
    \\    var pool = try Node.Pool.init(allocator, pool_size);
    \\    defer pool.deinit();
    \\    const test_dir_name = try std.fs.path.join(allocator, &[_][]const u8{{
    \\        spec_test_options.spec_test_out_dir,
    \\        spec_test_options.spec_test_version,
    \\        @tagName(active_preset) ++ "/tests/" ++ @tagName(active_preset) ++ "/{s}/fork_choice/{s}/pyspec_tests/{s}",
    \\    }});
    \\    defer allocator.free(test_dir_name);
    \\    const test_dir = std.fs.cwd().openDir(test_dir_name, .{{}}) catch return error.SkipZigTest;
    \\
    \\    try ForkChoiceRunner.TestCase(.{s}).execute(allocator, &pool, test_dir);
    \\}}
    \\
    \\
;

pub fn writeHeader(writer: std.io.AnyWriter) !void {
    try writer.print(header, .{});
}

/// Tests skipped to match Lodestar TS unstable.
/// TODO GLOAS: proposer boost specs changed retroactively in v1.7.0-alpha.1;
/// remove once update_proposer_boost_root is implemented.
/// invalid_incorrect_proof: no KZG verification for minimal preset.
const skip_patterns = [_][]const u8{
    "voting_source_beyond_two_epoch",
    "justified_update_always_if_better",
    "justified_update_not_realized_finality",
    "invalid_incorrect_proof",
};

fn shouldSkip(test_case_name: []const u8) bool {
    for (skip_patterns) |pattern| {
        if (std.mem.indexOf(u8, test_case_name, pattern) != null) return true;
    }
    return false;
}

pub fn writeTest(
    writer: std.io.AnyWriter,
    fork: ForkSeq,
    handler: Handler,
    test_case_name: []const u8,
) !void {
    if (shouldSkip(test_case_name)) return;

    try writer.print(test_template, .{
        @tagName(fork),
        @tagName(handler),
        test_case_name,

        @tagName(fork),
        @tagName(handler),
        test_case_name,

        @tagName(fork),
    });
}
