const std = @import("std");
const Allocator = std.mem.Allocator;

const spec_test_options = @import("spec_test_options");

const io = std.Options.debug_io;

pub fn main() !void {
    const allocator = std.heap.smp_allocator;
    const tests = &[_][]const u8{
        "general",
        "minimal",
        "mainnet",
    };
    try write_version();
    for (tests) |test_name| {
        try download_and_extract_spec_test(
            allocator,
            spec_test_options.spec_test_url,
            spec_test_options.spec_test_version,
            test_name,
            spec_test_options.spec_test_out_dir,
        );
    }
}

fn write_version() !void {
    const version_file = try std.Io.Dir.cwd().createFile(io, "test/spec/version.txt", .{});
    defer version_file.close(io);

    var write_buf: [4096]u8 = undefined;
    var file_writer = version_file.writer(io, &write_buf);
    var writer = &file_writer.interface;
    try writer.print(
        \\// This file is generated by download_spec_tests.zig.
        \\// This file exists as a cache key for the spec tests in CI.
        \\// Do not commit changes by hand.
        \\
        \\{s}
        \\
    , .{spec_test_options.spec_test_version});
    try file_writer.end();
}

fn download_and_extract_spec_test(
    allocator: Allocator,
    spec_test_url: []const u8,
    spec_test_version: []const u8,
    test_name: []const u8,
    out_dir: []const u8,
) !void {
    try download_spec_test_archive(allocator, spec_test_url, spec_test_version, test_name, out_dir);
    try extract_spec_test_archive(allocator, spec_test_version, test_name, out_dir);
}

fn download_spec_test_archive(
    allocator: Allocator,
    spec_test_url: []const u8,
    spec_test_version: []const u8,
    test_name: []const u8,
    out_dir: []const u8,
) !void {
    const filename = try std.fmt.allocPrint(allocator, "{s}.tar.gz", .{test_name});
    defer allocator.free(filename);

    const archive_dirname = try std.fs.path.join(allocator, &[_][]const u8{ out_dir, spec_test_version });
    defer allocator.free(archive_dirname);

    std.Io.Dir.cwd().createDirPath(io, archive_dirname) catch |err| {
        if (err != error.PathAlreadyExists) {
            return err;
        }
    };
    const archive_dir = try std.Io.Dir.cwd().openDir(io, archive_dirname, .{});

    const already_downloaded = archive_dir.openFile(io, filename, .{}) catch null;
    if (already_downloaded != null) {
        std.log.info("already downloaded {s}", .{filename});
        already_downloaded.?.close(io);
        return;
    }

    std.log.info("downloading spec test {s} {s}", .{ spec_test_version, test_name });

    var client: std.http.Client = .{ .allocator = allocator, .io = io };
    defer client.deinit();

    const url = try std.fmt.allocPrint(
        allocator,
        "{s}/releases/download/{s}/{s}.tar.gz",
        .{ spec_test_url, spec_test_version, test_name },
    );
    defer allocator.free(url);

    std.log.info("spec test url: {s}", .{url});

    // Download to memory first, then write to disk
    var response_writer: std.Io.Writer.Allocating = .init(allocator);
    defer response_writer.deinit();

    const result = try client.fetch(.{
        .location = .{ .url = url },
        .response_writer = &response_writer.writer,
    });

    if (result.status.class() != .success) {
        std.log.err("Failed to download: HTTP {d}", .{@intFromEnum(result.status)});
        return error.DownloadFailed;
    }

    const body = response_writer.written();
    std.log.info("downloaded {d} bytes, writing to disk - {s}", .{ body.len, filename });

    const file = try archive_dir.createFile(io, filename, .{});
    defer file.close(io);

    var write_buf: [8192]u8 = undefined;
    var fw = file.writer(io, &write_buf);
    try fw.interface.writeAll(body);
    try fw.end();

    std.log.info("response written to disk", .{});
}

fn extract_spec_test_archive(
    allocator: Allocator,
    spec_test_version: []const u8,
    test_name: []const u8,
    out_dir: []const u8,
) !void {
    const archive_dirname = try std.fs.path.join(allocator, &[_][]const u8{ out_dir, spec_test_version });
    defer allocator.free(archive_dirname);

    const filename = try std.fmt.allocPrint(allocator, "{s}.tar.gz", .{test_name});
    defer allocator.free(filename);

    var archive_dir = try std.Io.Dir.cwd().openDir(io, archive_dirname, .{});
    defer archive_dir.close(io);

    // Check for a marker file that indicates successful extraction.
    const marker_name = try std.fmt.allocPrint(allocator, "{s}.extracted", .{test_name});
    defer allocator.free(marker_name);

    if (archive_dir.openFile(io, marker_name, .{})) |marker| {
        std.log.info("already extracted {s}", .{filename});
        marker.close(io);
        return;
    } else |err| {
        if (err != error.FileNotFound) {
            return err;
        }
    }

    const archive_file = try archive_dir.openFile(io, filename, .{});
    defer archive_file.close(io);

    archive_dir.createDir(io, test_name, .default_dir) catch |err| {
        if (err != error.PathAlreadyExists) {
            return err;
        }
    };

    std.log.info("extracting {s}", .{filename});

    var extract_dir = try archive_dir.openDir(io, test_name, .{});
    defer extract_dir.close(io);

    // Read the gzip-compressed tar archive and pipe it to the file system.
    var read_buf: [std.compress.flate.max_window_len * 2]u8 = undefined;
    var file_reader = archive_file.reader(io, read_buf[0..std.compress.flate.max_window_len]);
    var decompress_buf: [std.compress.flate.max_window_len * 2]u8 = undefined;
    var decompressor = std.compress.flate.Decompress.init(
        &file_reader.interface,
        .gzip,
        &decompress_buf,
    );

    try std.tar.pipeToFileSystem(io, extract_dir, &decompressor.reader, .{
        .strip_components = 1,
        .diagnostics = null,
    });

    std.log.info("extracted {s}", .{filename});

    // Write marker file to indicate successful extraction.
    const marker_name2 = try std.fmt.allocPrint(allocator, "{s}.extracted", .{test_name});
    defer allocator.free(marker_name2);
    const marker = try archive_dir.createFile(io, marker_name2, .{});
    marker.close(io);
}
