const std = @import("std");
const ForkSeq = @import("config").ForkSeq;
const spec_test_options = @import("spec_test_options");
const RunnerKind = @import("./runner_kind.zig").RunnerKind;

const supported_forks = [_]ForkSeq{
    .phase0,
    .altair,
    .bellatrix,
    .capella,
    .deneb,
    .electra,
    .fulu,
};

const supported_test_runners = [_]RunnerKind{
    .merkle_proof,
    .operations,
    .rewards,
    .sanity,
    .epoch_processing,
    .fork,
    .transition,
    .random,
    .finality,
};

fn TestWriter(comptime kind: RunnerKind) type {
    return switch (kind) {
        .merkle_proof => @import("./writer/merkle_proof.zig"),
        .operations => @import("./writer/operations.zig"),
        .rewards => @import("./writer/rewards.zig"),
        .sanity => @import("./writer/sanity.zig"),
        .epoch_processing => @import("./writer/epoch_processing.zig"),
        .fork => @import("./writer/fork.zig"),
        .transition => @import("./writer/transition.zig"),
        .random => @import("./writer/random.zig"),
        .finality => @import("./writer/finality.zig"),
        else => @compileError("Unsupported test runner"),
    };
}

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const test_case_dir = "test/spec/test_case/";
    try std.Io.Dir.createDirPath(.cwd(), io, test_case_dir);

    inline for (supported_test_runners) |kind| {
        const test_case_file = test_case_dir ++ @tagName(kind) ++ "_tests.zig";
        const out = try std.Io.Dir.createFile(.cwd(), io, test_case_file, .{});
        defer out.close(io);

        var write_buf: [8 * 1024]u8 = undefined;
        var writer = out.writer(io, &write_buf);
        try writeTests(io, &supported_forks, kind, &writer.interface);
        try writer.flush();
    }

    {
        const test_root_file = "test/spec/root.zig";
        try std.Io.Dir.createDirPath(.cwd(), io, "test/spec");
        const out = try std.Io.Dir.createFile(.cwd(), io, test_root_file, .{});
        defer out.close(io);
        var write_buf: [8 * 1024]u8 = undefined;
        var writer = out.writer(io, &write_buf);
        try writeTestRoot(&supported_test_runners, &writer.interface);
        try writer.flush();
    }
}

pub fn writeTestRoot(comptime kinds: []const RunnerKind, writer: *std.Io.Writer) !void {
    try writer.print(
        \\// This file is generated by write_spec_tests.zig.
        \\// Do not commit changes by hand.
        \\
        \\const testing = @import("std").testing;
        \\
        \\comptime {{
        \\
    , .{});
    inline for (kinds) |kind| {
        try writer.print(
            \\    testing.refAllDecls(@import("./test_case/{s}_tests.zig"));
            \\
        , .{@tagName(kind)});
    }
    try writer.print(
        \\}}
        \\
    , .{});
}

pub fn writeTests(
    io: std.Io,
    comptime forks: []const ForkSeq,
    comptime kind: RunnerKind,
    writer: *std.Io.Writer,
) !void {
    try TestWriter(kind).writeHeader(writer);

    var root_dir = try std.Io.Dir.openDir(.cwd(), io, spec_test_options.spec_test_out_dir ++ "/" ++ spec_test_options.spec_test_version, .{});
    defer root_dir.close(io);

    // minimal preset includes many more testcases and is a superset of mainnet testcases
    var preset_dir = try root_dir.openDir(io, "minimal/tests/minimal", .{});
    defer preset_dir.close(io);

    inline for (forks) |fork| {
        const fork_path = @tagName(fork) ++ "/" ++ @tagName(kind);
        const maybe_fork_dir = preset_dir.openDir(io, fork_path, .{ .iterate = true }) catch |err| switch (err) {
            error.FileNotFound => null,
            else => return err,
        };

        if (maybe_fork_dir) |dir| {
            var fork_dir = dir;
            defer fork_dir.close(io);

            inline for (TestWriter(kind).handlers) |handler| handler_loop: {
                var suite_dir = fork_dir.openDir(io, comptime handler.suiteName(), .{ .iterate = true }) catch |err| switch (err) {
                    error.FileNotFound => break :handler_loop,
                    else => return err,
                };
                defer suite_dir.close(io);

                var suite_iter = suite_dir.iterate();
                while (try suite_iter.next(io)) |suite_entry| {
                    if (suite_entry.kind != .directory) continue;

                    if (comptime kind.hasSuiteCase()) {
                        var case_dir = suite_dir.openDir(io, suite_entry.name, .{ .iterate = true }) catch continue;
                        defer case_dir.close(io);

                        var case_iter = case_dir.iterate();
                        while (try case_iter.next(io)) |case_entry| {
                            if (case_entry.kind != .directory) continue;
                            try TestWriter(kind).writeTest(writer, fork, handler, suite_entry.name, case_entry.name);
                        }
                    } else {
                        try TestWriter(kind).writeTest(writer, fork, handler, suite_entry.name);
                    }
                }
            }
        }
    }
}
