const std = @import("std");
const types = @import("consensus_types");
pub const bls = @import("bls");
const PublicKey = bls.PublicKey;
const Signature = bls.Signature;
const Root = types.primitive.Root.Type;
const BLSSignature = types.primitive.BLSSignature.Type;
const verify = @import("./bls.zig").verify;
const fastAggregateVerify = @import("./bls.zig").fastAggregateVerify;

pub const SignatureSetType = enum { single, aggregate };

pub const SingleSignatureSet = struct {
    // fromBytes api return PublicKey so it's more convenient to model this as value
    pubkey: PublicKey,
    signing_root: Root,
    signature: BLSSignature,
};

pub const AggregatedSignatureSet = struct {
    // fastAggregateVerify also requires []*const PublicKey
    pubkeys: []const PublicKey,
    signing_root: Root,
    signature: BLSSignature,
};

fn uncompressAndGroupCheck(encoded: *const BLSSignature) !?Signature {
    const signature = try Signature.uncompress(encoded);
    signature.validate(false) catch |err| {
        if (err == bls.BlstError.PointNotInGroup) return null;
        return err;
    };
    return signature;
}

pub fn verifySingleSignatureSet(set: *const SingleSignatureSet) !bool {
    const signature = try uncompressAndGroupCheck(&set.signature) orelse return false;
    if (verify(&set.signing_root, &set.pubkey, &signature, .{ .sig_groupcheck = false })) {
        return true;
    } else |_| {
        return false;
    }
}

pub fn verifyAggregatedSignatureSet(set: *const AggregatedSignatureSet) !bool {
    const signature = try uncompressAndGroupCheck(&set.signature) orelse return false;
    return fastAggregateVerify(
        &set.signing_root,
        set.pubkeys,
        &signature,
        .{ .sig_groupcheck = false },
    );
}

pub fn createSingleSignatureSetFromComponents(pubkey: *const PublicKey, signing_root: Root, signature: BLSSignature) SingleSignatureSet {
    return .{
        .pubkey = pubkey,
        .signing_root = signing_root,
        .signature = signature,
    };
}

pub fn createAggregateSignatureSetFromComponents(pubkeys: []const PublicKey, signing_root: Root, signature: BLSSignature) AggregatedSignatureSet {
    return .{
        .pubkeys = pubkeys,
        .signing_root = signing_root,
        .signature = signature,
    };
}

test "signature sets reject signatures outside G2 subgroup" {
    const ikm = [_]u8{1} ** 32;
    const signing_root = [_]u8{2} ** 32;
    const secret_key = try bls.SecretKey.keyGen(&ikm, null);
    const public_key = secret_key.toPublicKey();
    const valid_signature = secret_key.sign(&signing_root, bls.DST, null);
    const valid_signature_bytes = valid_signature.compress();

    // Generated by adding [r]P to the valid signature, where P is the first decodable compressed
    // curve point with an x-coordinate in the range 0...255.
    var forged_signature_bytes: BLSSignature = undefined;
    _ = try std.fmt.hexToBytes(
        &forged_signature_bytes,
        "99de7bff0cf5337f1d09fec80f5c9f5af01436b61656692b9520ca79f8211266" ++
            "8bbedce24f69d56c171a39b0425e508017c04962b77d77d80233bd92f45ba9bb" ++
            "93917964f576e8c5a1d2b9487c1e9b0d99021fb8ecfe5fec421d41c19674b609",
    );
    const forged_signature = try Signature.uncompress(&forged_signature_bytes);
    try std.testing.expect(!forged_signature.subgroupCheck());

    // Check the validation boundary directly because final verification also rejects this vector
    // when subgroup checking is disabled.
    try std.testing.expect((try uncompressAndGroupCheck(&forged_signature_bytes)) == null);
    try std.testing.expect((try uncompressAndGroupCheck(&valid_signature_bytes)) != null);

    const public_keys = [_]PublicKey{public_key};

    const single_forged = SingleSignatureSet{
        .pubkey = public_key,
        .signing_root = signing_root,
        .signature = forged_signature_bytes,
    };
    try std.testing.expect(!try verifySingleSignatureSet(&single_forged));

    const aggregate_forged = AggregatedSignatureSet{
        .pubkeys = &public_keys,
        .signing_root = signing_root,
        .signature = forged_signature_bytes,
    };
    try std.testing.expect(!try verifyAggregatedSignatureSet(&aggregate_forged));

    const single_valid = SingleSignatureSet{
        .pubkey = public_key,
        .signing_root = signing_root,
        .signature = valid_signature_bytes,
    };
    try std.testing.expect(try verifySingleSignatureSet(&single_valid));

    const aggregate_valid = AggregatedSignatureSet{
        .pubkeys = &public_keys,
        .signing_root = signing_root,
        .signature = valid_signature_bytes,
    };
    try std.testing.expect(try verifyAggregatedSignatureSet(&aggregate_valid));
}
