const std = @import("std");
const options = @import("spec_test_options");

const suites = [_][]const u8{
    "test_basic_types",
    "test_compatible_unions",
    "test_decode_failure_smoke",
    "test_merkleization_boundaries",
    "test_progressive_containers",
    "test_progressive_types",
};

pub fn main(init: std.process.Init) !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    const io = init.io;
    const fixtures_path = try std.fs.path.join(allocator, &.{ options.spec_test_out_dir, "ssz", options.ssz_spec_test_version, "fixtures/ssz/ssz" });
    var fixtures = try std.Io.Dir.cwd().openDir(io, fixtures_path, .{ .iterate = true });
    defer fixtures.close(io);
    var directories = fixtures.iterate();
    var suite_count: usize = 0;
    while (try directories.next(io)) |entry| {
        if (entry.kind != .directory) continue;
        var known = false;
        for (suites) |suite| {
            if (std.mem.eql(u8, suite, entry.name)) known = true;
        }
        if (!known) {
            std.log.err("unsupported SSZ fixture suite: {s}", .{entry.name});
            return error.UnknownSuite;
        }
        suite_count += 1;
    }
    if (suite_count != suites.len) return error.MissingSuite;

    // Only replace the generated file after every suite has been inspected.
    // Missing or unsupported fixtures must not turn the target into zero tests.
    var buffer = std.Io.Writer.Allocating.init(allocator);
    const writer = &buffer.writer;
    try writer.writeAll(
        \\// This file is generated by write_generic_tests.zig.
        \\// Do not commit changes by hand.
        \\const std = @import("std");
        \\const options = @import("spec_test_options");
        \\const types = @import("json_types.zig");
        \\const test_case = @import("json_test_case.zig");
        \\
        \\
    );
    var total: usize = 0;
    var invalid: usize = 0;
    for (suites) |suite| {
        var dir = try fixtures.openDir(io, suite, .{ .iterate = true });
        defer dir.close(io);
        var names: std.ArrayList([]const u8) = .empty;
        var it = dir.iterate();
        while (try it.next(io)) |entry| {
            if (entry.kind == .file and std.mem.endsWith(u8, entry.name, ".json")) try names.append(allocator, try allocator.dupe(u8, entry.name));
        }
        if (names.items.len == 0) return error.EmptySuite;
        std.mem.sort([]const u8, names.items, {}, struct {
            fn less(_: void, a: []const u8, b: []const u8) bool {
                return std.mem.lessThan(u8, a, b);
            }
        }.less);
        var suite_tests: usize = 0;
        for (names.items) |name| {
            const source = try dir.readFileAlloc(io, name, allocator, .limited(16 * 1024 * 1024));
            const json = try std.json.parseFromSlice(std.json.Value, allocator, source, .{ .parse_numbers = false });
            if (json.value != .object or json.value.object.count() == 0) return error.InvalidFixture;
            var cases = json.value.object.iterator();
            while (cases.next()) |entry| {
                const fixture = entry.value_ptr.*;
                const type_name = (fixture.object.get("typeName") orelse return error.MissingType).string;
                // Generated references make an unknown type a compile error. Require
                // identifiers here so fixture text cannot introduce Zig source.
                if (!std.zig.isValidId(type_name)) return error.InvalidTypeName;
                try writer.print(
                    \\test "{s}/{f}" {{
                    \\    const path = try std.fs.path.join(std.testing.allocator, &.{{ options.spec_test_out_dir, "ssz", options.ssz_spec_test_version, "fixtures/ssz/ssz/{s}/{f}" }});
                    \\    defer std.testing.allocator.free(path);
                    \\    try test_case.run(types.{s}.{s}, std.testing.allocator, path, "{f}");
                    \\}}
                    \\
                    \\
                , .{ suite, std.zig.fmtString(entry.key_ptr.*), suite, std.zig.fmtString(name), suite, type_name, std.zig.fmtString(entry.key_ptr.*) });
                total += 1;
                suite_tests += 1;
                if (fixture.object.contains("rejectionReason")) invalid += 1;
            }
        }
        std.log.info("SSZ {s}: {d} cases", .{ suite, suite_tests });
    }
    if (total == 0) return error.EmptyFixtures;
    const out = try std.Io.Dir.cwd().createFile(io, "test/spec/ssz/generic_tests.zig", .{});
    defer out.close(io);
    try out.writeStreamingAll(io, buffer.written());
    std.log.info("generated {d} SSZ cases ({d} valid, {d} invalid), pin {s}", .{ total, total - invalid, invalid, options.ssz_spec_test_version });
}
