const std = @import("std");
const spec_test_options = @import("spec_test_options");

pub fn main(init: std.process.Init) !void {
    const allocator = std.heap.page_allocator;
    const io = init.io;

    // minimal preset includes many more testcases
    // so use that for generating tests
    const preset_str = "minimal";

    const out = try std.Io.Dir.createFile(.cwd(), io, "test/spec/ssz/static_tests.zig", .{});
    defer out.close(io);

    var write_buf: [8 * 1024]u8 = undefined;
    var file_writer = out.writer(io, &write_buf);
    var writer = &file_writer.interface;

    try writer.writeAll(
        \\// This file is generated by write_static_tests.zig.
        \\// Do not commit changes by hand.
        \\
        \\const std = @import("std");
        \\const spec_test_options = @import("spec_test_options");
        \\const build_options = @import("build_options");
        \\const types = @import("consensus_types");
        \\const test_case = @import("test_case.zig");
        \\
        \\const allocator = std.testing.allocator;
        \\
        \\
    );

    const preset_tests_dir_name = try std.fs.path.join(allocator, &[_][]const u8{
        spec_test_options.spec_test_out_dir,
        spec_test_options.spec_test_version,
        preset_str,
        "tests",
        preset_str,
    });
    defer allocator.free(preset_tests_dir_name);

    const supported_forks = [_][]const u8{
        "phase0",
        "altair",
        "bellatrix",
        "capella",
        "deneb",
        "electra",
        "fulu",
        "gloas",
    };

    for (supported_forks) |fork| {
        const static_tests_dir_name = try std.fs.path.join(allocator, &[_][]const u8{
            preset_tests_dir_name,
            fork,
            "ssz_static",
        });
        defer allocator.free(static_tests_dir_name);

        const static_tests_dir = try std.Io.Dir.openDir(.cwd(), io, static_tests_dir_name, .{ .iterate = true });
        defer static_tests_dir.close(io);
        var static_tests_dir_it = static_tests_dir.iterate();
        while (try static_tests_dir_it.next(io)) |g_test_entry| {
            switch (g_test_entry.kind) {
                .directory => {},
                else => {
                    continue;
                },
            }

            const type_name = g_test_entry.name;
            // Partial-column DAS types are not implemented yet. Keep this list
            // aligned with Lodestar's specTestIterator.ts; state-transition
            // containers and all other Gloas types remain required.
            if (unsupportedPartialColumnType(fork, type_name)) {
                std.log.info("unsupported SSZ static type: {s}/{s}", .{ fork, type_name });
                continue;
            }

            const type_name_tests_dir_name = try std.fs.path.join(allocator, &[_][]const u8{
                static_tests_dir_name,
                type_name,
            });
            defer allocator.free(type_name_tests_dir_name);

            const type_name_tests_dir = try std.Io.Dir.openDir(.cwd(), io, type_name_tests_dir_name, .{ .iterate = true });
            defer type_name_tests_dir.close(io);
            var type_name_tests_dir_it = type_name_tests_dir.iterate();
            while (try type_name_tests_dir_it.next(io)) |type_name_test_entry| {
                switch (type_name_test_entry.kind) {
                    .directory => {},
                    else => {
                        continue;
                    },
                }

                const test_suite_name = type_name_test_entry.name;

                const test_suite_dir_name = try std.fs.path.join(allocator, &[_][]const u8{
                    type_name_tests_dir_name,
                    test_suite_name,
                });
                defer allocator.free(test_suite_dir_name);

                const test_suite_dir = try std.Io.Dir.openDir(.cwd(), io, test_suite_dir_name, .{ .iterate = true });
                defer test_suite_dir.close(io);
                var test_suite_dir_it = test_suite_dir.iterate();
                while (try test_suite_dir_it.next(io)) |test_suite_entry| {
                    switch (test_suite_entry.kind) {
                        .directory => {},
                        else => {
                            continue;
                        },
                    }

                    const test_case_name = test_suite_entry.name;

                    try writeStaticTest(
                        writer,
                        fork,
                        type_name,
                        test_suite_name,
                        test_case_name,
                    );
                }
            }
        }
    }

    try file_writer.flush();
}

fn unsupportedPartialColumnType(fork: []const u8, type_name: []const u8) bool {
    if (!std.mem.eql(u8, fork, "fulu") and !std.mem.eql(u8, fork, "gloas")) return false;
    if (std.mem.eql(u8, fork, "fulu") and std.mem.eql(u8, type_name, "PartialDataColumnHeader")) return true;
    const unsupported = [_][]const u8{
        "PartialDataColumnGroupID",
        "PartialDataColumnPartsMetadata",
        "PartialDataColumnSidecar",
    };
    for (unsupported) |name| {
        if (std.mem.eql(u8, name, type_name)) return true;
    }
    return false;
}

/// Assumes the following global decls
/// - std, allocator, spec_test_options, generic_tests_dir_name, test_case, {tests_dir}, types.{type_name}
fn writeStaticTest(
    writer: *std.Io.Writer,
    fork: []const u8,
    type_name: []const u8,
    test_suite_name: []const u8,
    test_name: []const u8,
) !void {
    try writer.print(
        \\test "Static - {s} {s} {s} {s}" {{
        \\    const test_dir_name = try std.fs.path.join(allocator, &[_][]const u8{{
        \\        spec_test_options.spec_test_out_dir,
        \\        spec_test_options.spec_test_version,
        \\        build_options.preset,
        \\        "tests",
        \\        build_options.preset,
        \\        "{s}/ssz_static/{s}/{s}/{s}",
        \\    }});
        \\    defer allocator.free(test_dir_name);
        \\
        \\    var test_dir = std.Io.Dir.openDir(.cwd(), std.testing.io, test_dir_name, .{{}}) catch |err| switch (err) {{
        \\        error.FileNotFound => return error.SkipZigTest,
        \\        else => return err,
        \\    }};
        \\    defer test_dir.close(std.testing.io);
        \\    try test_case.validTestCase(types.{s}.{s}, allocator, test_dir, "roots.yaml");
        \\}}
        \\
        \\
    ,
        .{
            fork,
            type_name,
            test_suite_name,
            test_name,
            fork,
            type_name,
            test_suite_name,
            test_name,
            fork,
            type_name,
        },
    );
}
