const std = @import("std");
const fixtures = @import("fixtures.zig");
const types = @import("generic_types.zig");

pub fn main(init: std.process.Init) !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    const io = init.io;

    const out = try std.Io.Dir.createFile(.cwd(), io, "test/spec/ssz/generic_tests.zig", .{});
    defer out.close(io);

    var write_buf: [8 * 1024]u8 = undefined;
    var file_writer = out.writer(io, &write_buf);
    var writer = &file_writer.interface;

    try writer.writeAll(
        \\// This file is generated by write_generic_tests.zig.
        \\// Do not commit changes by hand.
        \\
        \\const std = @import("std");
        \\const fixtures = @import("fixtures.zig");
        \\const types = @import("generic_types.zig");
        \\const test_case = @import("test_case.zig");
        \\
        \\const allocator = std.testing.allocator;
        \\
        \\
    );

    const fixtures_dir = try std.Io.Dir.openDir(.cwd(), io, fixtures.fixtures_dir, .{ .iterate = true });
    for (try sortedEntryNames(allocator, io, fixtures_dir, .directory)) |suite| {
        const suite_dir = try fixtures_dir.openDir(io, suite, .{ .iterate = true });
        for (try sortedEntryNames(allocator, io, suite_dir, .file)) |file_name| {
            if (!std.mem.endsWith(u8, file_name, ".json")) continue;

            const json_bytes = try suite_dir.readFileAlloc(io, file_name, allocator, .unlimited);
            const json = try std.json.parseFromSliceLeaky(std.json.Value, allocator, json_bytes, .{});

            var it = json.object.iterator();
            while (it.next()) |entry| {
                const test_id = entry.key_ptr.*;
                const fixture = entry.value_ptr.object;
                const type_name = fixture.get("typeName").?.string;
                const is_valid = fixture.get("rejectionReason") == null;

                if (!hasType(suite, type_name)) {
                    std.log.warn("skipping {s} - {s}: {s} is not declared in generic_types.zig", .{ suite, testName(test_id), type_name });
                    continue;
                }

                try writer.print(
                    \\test "{s} - {s}" {{
                    \\    try test_case.{s}(
                    \\        types.{s}.{s},
                    \\        allocator,
                    \\        fixtures.fixtures_dir ++ "/{s}/{s}",
                    \\        "{s}",
                    \\    );
                    \\}}
                    \\
                    \\
                , .{
                    suite,
                    testName(test_id),
                    if (is_valid) "validJsonTestCase" else "invalidJsonTestCase",
                    suite,
                    type_name,
                    suite,
                    file_name,
                    test_id,
                });
            }
        }
    }

    try file_writer.flush();
}

fn hasType(suite: []const u8, type_name: []const u8) bool {
    inline for (@typeInfo(types).@"struct".decls) |suite_decl| {
        if (std.mem.eql(u8, suite_decl.name, suite)) {
            inline for (@typeInfo(@field(types, suite_decl.name)).@"struct".decls) |type_decl| {
                if (std.mem.eql(u8, type_decl.name, type_name)) return true;
            }
            return false;
        }
    }
    return false;
}

/// Test ids look like `tests/fillers/ssz/test_basic_types.py::test_boolean_true[ssz_test]`.
fn testName(test_id: []const u8) []const u8 {
    const start = if (std.mem.lastIndexOf(u8, test_id, "::")) |i| i + 2 else 0;
    return test_id[start..];
}

fn sortedEntryNames(
    allocator: std.mem.Allocator,
    io: std.Io,
    dir: std.Io.Dir,
    kind: std.Io.File.Kind,
) ![]const []const u8 {
    var names: std.ArrayList([]const u8) = .empty;
    var it = dir.iterate();
    while (try it.next(io)) |entry| {
        if (entry.kind != kind) continue;
        try names.append(allocator, try allocator.dupe(u8, entry.name));
    }
    std.mem.sort([]const u8, names.items, {}, lessThan);
    return names.items;
}

fn lessThan(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.lessThan(u8, a, b);
}
