// Independently signed by @chainsafe/enr 6.0.2; scalar 1, sequence 7.
// See enr-reference.mjs and enr-vectors.json for provenance and SHA-256 values.
pub const vectors = .{
    .{ .name = "ipv4", .text = "enr:-Mu4QJu5uLuoJkU6ua199lEhTRBu8CkCPJ9gh3eUnnAzSY_pLCAYrqn1A5ggvbbseErV92G1jIo6f46Pkoak3Onqa8sHh2F0dG5ldHOIAQAAAAAAAICDY2djBIRldGgykAECAwQFAAAA__________-CaWSCdjSCaXCEfwAAAYNuZmSECQoLDIRxdWljgiMpiXNlY3AyNTZrMaECeb5mfvncu6xVoGKVzocLBwKb_NstzijZWfKBWxb4F5iIc3luY25ldHMFg3VkcIIjKA" },
    .{ .name = "dual_stack", .text = "enr:-PG4QDhfJYflECsjObJE39ncLYkzMduKMAFcDmRcBF3Edsp5Aw8R4HmV8m1YKKs1qDvVo8lmbgZUIR_7CrgldguabQ4Hh2F0dG5ldHOIAQAAAAAAAICDY2djBIRldGgykAECAwQFAAAA__________-CaWSCdjSCaXCEfwAAAYNpcDaQAAAAAAAAAAAAAAAAAAAAAYNuZmSECQoLDIRxdWljgiMphXF1aWM2giONiXNlY3AyNTZrMaECeb5mfvncu6xVoGKVzocLBwKb_NstzijZWfKBWxb4F5iIc3luY25ldHMFg3VkcIIjKIR1ZHA2giOM" },
    .{ .name = "no_quic", .text = "enr:-MO4QMoPy75sWZ6NPP53pXrcAtSL8_JXVPXzgGiImvciGMRKcIDCMxobI_mgY_ATtg9DI2sh9jrAFJ-JOf4lNVM8aOQHh2F0dG5ldHOIAQAAAAAAAICDY2djBIRldGgykAECAwQFAAAA__________-CaWSCdjSCaXCEfwAAAYNuZmSECQoLDIlzZWNwMjU2azGhAnm-Zn753LusVaBilc6HCwcCm_zbLc4o2VnygVsW-BeYiHN5bmNuZXRzBYN1ZHCCIyg" },
    .{ .name = "sync_upper_bits", .text = "enr:-Mu4QF2ITIDhYQVFhs6dVcqorRXUBlV-VMOdhE41S3ceIQpwZ3yb8F3doGFrEHPeu2_ESDOiWUzmeuVcifRufAUq5_AHh2F0dG5ldHOIAQAAAAAAAICDY2djBIRldGgykAECAwQFAAAA__________-CaWSCdjSCaXCEfwAAAYNuZmSECQoLDIRxdWljgiMpiXNlY3AyNTZrMaECeb5mfvncu6xVoGKVzocLBwKb_NstzijZWfKBWxb4F5iIc3luY25ldHMQg3VkcIIjKA" },
    .{ .name = "cgc_leading_zero", .text = "enr:-M24QKFTda2aJavVUS0H3NwNiHRWzeIYF5UwPj9pIEu1jC0uGTM6dIrXZ5oN9_HthdcZCnYiuziNBjPJwkIs7zQsddEHh2F0dG5ldHOIAQAAAAAAAICDY2djggAEhGV0aDKQAQIDBAUAAAD__________4JpZIJ2NIJpcIR_AAABg25mZIQJCgsMhHF1aWOCIymJc2VjcDI1NmsxoQJ5vmZ--dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmIhzeW5jbmV0cwWDdWRwgiMo" },
    .{ .name = "cgc_zero", .text = "enr:-Mu4QFrLdmlG-VVMiR1hFTUXy3LFrER5A6qASvrDCoyk_dLtJ4-e-mxtC_VNBfhnsqo07iIArnDxWNDdBeUiz4AGkXAHh2F0dG5ldHOIAQAAAAAAAICDY2djgIRldGgykAECAwQFAAAA__________-CaWSCdjSCaXCEfwAAAYNuZmSECQoLDIRxdWljgiMpiXNlY3AyNTZrMaECeb5mfvncu6xVoGKVzocLBwKb_NstzijZWfKBWxb4F5iIc3luY25ldHMFg3VkcIIjKA" },
    .{ .name = "cgc_over_128", .text = "enr:-My4QM1suIXimsojbwOF1ss58lqRBfDTUArxoCp1GsKI-KlpUp0imAgskhkMG5-umZkKvn2KKqHusSIkO9psYFzgYw8Hh2F0dG5ldHOIAQAAAAAAAICDY2djgYGEZXRoMpABAgMEBQAAAP__________gmlkgnY0gmlwhH8AAAGDbmZkhAkKCwyEcXVpY4IjKYlzZWNwMjU2azGhAnm-Zn753LusVaBilc6HCwcCm_zbLc4o2VnygVsW-BeYiHN5bmNuZXRzBYN1ZHCCIyg" },
    .{ .name = "eth2_short", .text = "enr:-L64QNBtGxWWKI8XF8wvquSYf5pl3dukAsmF_0KniTKqchFufQko_VcQ6h6mLpE-6pWGgvDbxDOJoDdn15-2EMb3TgQHh2F0dG5ldHOIAQAAAAAAAICDY2djBIRldGgygwECA4JpZIJ2NIJpcIR_AAABg25mZIQJCgsMhHF1aWOCIymJc2VjcDI1NmsxoQJ5vmZ--dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmIhzeW5jbmV0cwWDdWRwgiMo" },
    .{ .name = "nfd_short", .text = "enr:-Me4QOGJMLstGnN-20VQPn1p4u7Q56OvMDhw7C1MahuMllPkFJKqAULo-fPc3_Rp4tQEnOziagQN2FQ6HOin3FYt2zQHh2F0dG5ldHOIAQAAAAAAAICDY2djBIRldGgykAECAwQFAAAA__________-CaWSCdjSCaXCEfwAAAYNuZmQBhHF1aWOCIymJc2VjcDI1NmsxoQJ5vmZ--dy7rFWgYpXOhwsHApv82y3OKNlZ8oFbFvgXmIhzeW5jbmV0cwWDdWRwgiMo" },
    .{ .name = "nfd_differs", .text = "enr:-Mu4QD29r_8h2mVt6_WTmiAilncyVC-H5v0Hn1W_XhMyVONFdklIcO3X5DdZCIL0CBVfDnKQEkZiaKwWVV4Ib7QgqMcHh2F0dG5ldHOIAQAAAAAAAICDY2djBIRldGgykAECAwQFAAAA__________-CaWSCdjSCaXCEfwAAAYNuZmSE_____4RxdWljgiMpiXNlY3AyNTZrMaECeb5mfvncu6xVoGKVzocLBwKb_NstzijZWfKBWxb4F5iIc3luY25ldHMFg3VkcIIjKA" },
    .{ .name = "fork_differs", .text = "enr:-Mu4QC22U9XmkGGNCdr_TaCkmL21X4WKtUE8CMsbIbP1VMZ6bJ5LTqS3oMl5yYLA4Zk_Rc3wLnWxYons7jT9IEoyXEoHh2F0dG5ldHOIAQAAAAAAAICDY2djBIRldGgykP____8FAAAA__________-CaWSCdjSCaXCEfwAAAYNuZmSECQoLDIRxdWljgiMpiXNlY3AyNTZrMaECeb5mfvncu6xVoGKVzocLBwKb_NstzijZWfKBWxb4F5iIc3luY25ldHMFg3VkcIIjKA" },
};
